title: Yang (Austin) Xiao
position: AI Engineer
affiliation: Fortemedia Singapore
email: yxiao009 (at) e.ntu.edu.sg
keywords: xiao yang ntu, yang xiao ntu
google_scholar: https://scholar.google.com/citations?user=lgcOwb4AAAAJ&hl=en
github_link: https://github.com/swagshaw
linkedin: https://www.linkedin.com/in/yangxiao1998
avatar: ./assets/img/IMG_202407016431_800x800.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/NTU.jpg
favicon_dark: ./assets/img/NTU.jpg
description: Yang (Austin) Xiao is a software engineer of audio and speech research. His interest is always focus on MLSys.
# canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
